In [1]:
import numpy as np
np.__version__

'1.18.5'

In [2]:
np.array([1,2,"1"])

array(['1', '2', '1'], dtype='<U11')

In [3]:
classic_list = [1, 2, 3, 5, 7, 11]
type(classic_list)

list

In [4]:
numpy_array = np.array(classic_list)
type(numpy_array)

numpy.ndarray

In [5]:
numpy_array.shape

(6,)

In [6]:
np.array([2,4]).mean()

3.0

In [8]:
numpy_matrix = np.array([[1,2,3], [5,7,13]])
numpy_matrix.shape

(2, 3)

In [10]:
matrix1 = np.array([
	[1,2,3],
	[4,5,6],
	[7,8,9]
])

In [11]:
matrix1[0, :]

array([1, 2, 3])

In [12]:
matrix1[:, -1]

array([3, 6, 9])

In [18]:
matrix1[2]

array([7, 8, 9])

In [20]:
matrix2 = np.array([
	[1,2,3],
	[0,8,10],
	[1,10,12]
])

In [21]:
matrix2.sum()

47

In [22]:
matrix2.sum(axis=0)

array([ 2, 20, 25])

In [23]:
matrix2.sum(axis=1)

array([ 6, 18, 23])

In [24]:
np.array([1,2]) + np.array([8,9])

array([ 9, 11])

In [27]:
np.array([
	[1,2],
	[3,4]
]) + \
np.array([
	[8,9],
	[10,11]
])

array([[ 9, 11],
       [13, 15]])

In [28]:
np.array([
	[1,2],
	[3,4]
]).dot([1,1])

array([3, 7])

In [32]:
np.array([1,2,3,4,5,6,7,8,9,10]) + np.full([1], 10)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
matrix3 = np.array([
	[1,2,3,4,5],
	[6,7,8,9,10],
	[11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])

In [71]:
# for x in matrix3:
#     x.mean()

In [67]:
np.average(matrix3[0, :])

3.0

In [60]:
b = matrix3[:, 0]
np.average(b)

11.0